language: python
python:
- 2.7
env:
  matrix:
    - DOCKER_CONTENT_TRUST=0
  global:
    - secure: ZkmYuhd/XZhV7FM7WjBVQo+KqeWdoZzZae/A5eCPHMvnNJul9f/pMwbHLgYOv1SBL4EgrSviL35lxJE0uziVMWg5tqzs+tRhZjkinUAOfFWlTx91rtzYCfvcoP0Yrm9Ccib99x36ILrCZlec+0P0kwOpMLk1FQYg8HLnI29gJKfJ+o2P7/o1MgcS7dgb8Cws03VlIM/7fVbkZ9MOL0NbwHMmYbQhEqNcOECXlPnD184iVCKSRwFGYjwxus2m9H1HnXVG5xDARlU1Sp7hVPKNwY1iImDqTugP1qhjBtBRGfI7JiNFVkGxvxZLb5W627LKmXXP1MTLkrFVEJjaTMyp0GaUEVK5qlt7kJlGPodh+MrmcZLREQUebxvLnvBqoPfROT5UdMF/hY1U+syEdoF2yfypNNmn7W1f7yRCCX8eJuVJY/Yq6Pr1IBjeKPOG1hKvV998cdZpjY+VtDAifu90/cWvNZhZCuT0/uNc/224ttTkQIJxyLkIxlN88a+0/q9ZEB3VMMBlO2XgcADgn6ftge9AWzRwOQBtfuz5Pf2HuHHvwaanV8BiiUHbka0hVMKhsql2ucJNB4DjAQivXbPgJVrQu05l56/INHLq5eNCqd1RaWTAkBQ83nK0M+6D87m+/H+3TE8FHxZENVFFGXpxvc7U7bvrz0QlBB6YAbvbbSE=
    - secure: jJOTkQ9vv/C/jM3Y/+PAxIddiaFaSMr2RRhmlpC4HJTMtcTFFMkhD4UUf0QSJT0UmmPB0q3muWBzSHpjpV45xztKjCt4eJq+c/+aLFBe0Lm6ta2UEVchn87rD1D9kbizivcdiPlsSYRnLqElsgyxadcGANYZ+Rm4sg88n0tw7AhTP83dPVR0iPFx9qeVppuqbHp9t57+qQp0j5uRekkNc8X4LNee64T1aCUpBFw0Pu8fPATyBtbDSu765NEEr6MyE7TNeyjs7sqd2daRfAi1NB9JVa+ZYE0OhPmJ2J+blYZs3KRqpPzr8OFIJHf9n7st3UGXRY1H2uaHxj+DkivSQ5tU2Qtt3v1uXInUS3xGYsTRzWMN+s4hX3HQ3CN1sOA41QquGPPGnAhVccz+WJTxU+pVaFD/clboLxvMrmRZHkhrGBJ9cehjOI9Wr19It/G9ayJTUIRMrB1NpQUvj6lOPs7xQHRX5Tgh7rZswtaWlu1tvyf0nd5oUKS/uLP15IYALZjKv3wJlj7J5Fof4qj9Nl4BNw9AOTIHyKsP/5sVqdAdNakH9Ec0bZZ4YhY1v7RLn4gWfCIugjmn4DFPpPM9bg1J9BSt8pMHR2lRo0QQ02K7DoNmjfUyBeBeTaVd2p01fZtd5Mdnm6IjGVLfltRXOVVSiDO+R+rtsN25bFfry3c=
services:
- docker
before_install:
- sudo apt-get update
- docker-compose --version
- pip install docker-compose
- docker-compose --version
install:
- cd v6/dockerfiles
- docker-compose build
- docker-compose up -d
- docker-compose ps
- docker-compose exec db bash -c /scripts/mysql.sh
- docker-compose exec pimcore sh -c './vendor/bin/pimcore-install --no-interaction --admin-username=pimcore --admin-password=pimcore --mysql-host-socket=db --mysql-username=root --mysql-password=root --mysql-database=pimcore'
- docker-compose exec pimcore bash -c 'chmod 0777 -R app/config bin composer.json pimcore var web/var'

before_script:
- cd $TRAVIS_BUILD_DIR
- pip install requests
- pip install docker
script:
- python tests.py
- bash ./.travis/linters.sh
notifications:
  slack:
    rooms:
    - optimum-team:GycletOWK4Kt95GktwYwfUMp#build
after_success:
- cd v6/dockerfiles
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- docker-compose -f docker-compose-build.yml images
- docker push trydirect/pimcore:6
